version: '3.5'
services:
  my_app_db:
    image: mariadb:10.1.34
    container_name: my_app_db
    restart: always
    environment:
      MYSQL_DATABASE: myapp_admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306
    networks:
    - mynetwork

  my_app_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_app_backend
    hostname: my_app_backend
    domainname: my_app_backend.com
    ports:
      - 8008:8008
    networks:
      - mynetwork
    volumes:
      - .:/app
    depends_on:
      - my_app_db

networks:
  mynetwork:
    external: true
    name: my-app-net


